# Generated by Django 4.0.5 on 2022-06-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='abc', max_length=50, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='abc', max_length=50, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default='123', verbose_name='telefono'),
        ),
    ]
